[build]
  command = "npm run build:events && npm run build:ui"
  publish = "build"
  functions = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"
